apiVersion: v1
kind: Service
metadata:
 name: devops-platform-svc
 labels:
  app: devops-platform
spec:
 type: NodePort
 selector:
  app: devops-platform
 ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080
